# Generated by Django 4.1.7 on 2023-03-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gdad", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gda",
            name="gene_pli",
            field=models.CharField(default="", max_length=15),
        ),
    ]
